spring:
  profiles:
    active: local
    group:
      local:
        - db
        - file
        - authmail
        - eureka
        - pay
      test:
        - db
        - file
        - authmail
        - eureka
        - pay
---
spring:
  config:
    activate:
      on-profile: local

# jpa 설정 부분
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false # osiv off
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  kafka:
    consumer:
      # bootstrap-servers: 27.96.131.242:9872 # Naver Cloud Platform
      bootstrap-servers: localhost:9872
      group-id: shopping-mall
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # bootstrap-servers: 27.96.131.242:9872 # Naver Cloud Platform
      bootstrap-servers: localhost:9872
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# zipkin 관련 설정
# spring: 하위에 작성 -> spring.zipkin.~~
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

#api 서버 포트
server:
  port: 10000

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

kafka:
  bootstrap:
    address: ${spring.embedded.kafka.brokers:localhost:9872}

