#api 서버 포트
server:
  port: 10000

# jpa 설정 부분
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/byun/h2/dbfile/h2_214/project/shoppingmall
#    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
