# jpa 설정 부분
spring:
  profiles:
    active: local
    include: file, authmail, eureka

  datasource:
    url: jdbc:h2:tcp://localhost/~/byun/h2/dbfile/h2_214/project/shoppingmall
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://127.0.0.1:3306/shop?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    open-in-view: false # osiv off

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

#api 서버 포트
server:
  port: 10000

---
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
